# Generated by Django 2.1b1 on 2018-07-21 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=200)),
                ('cat_id', models.CharField(max_length=50)),
                ('cat_stock', models.PositiveIntegerField()),
                ('cat_logo', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_id', models.CharField(max_length=100)),
                ('pr_name', models.CharField(max_length=500)),
                ('pr_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pr_stock', models.PositiveIntegerField()),
                ('pr_image', models.ImageField(upload_to='')),
                ('pr_mfg', models.DateTimeField(auto_now_add=True)),
                ('pr_avb', models.BooleanField(default=False)),
                ('pr_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Category')),
            ],
        ),
    ]
